model = "gpt-5-codex"
model_reasoning_effort = "high"

auto_commit = true
auto_push = true
auto_pr = true
auto_review_accept = true

approval_policy = "never"
sandbox_mode    = "danger-full-access"

[projects."/Users/colm/code"]
trust_level = "trusted"
